#!/usr/bin/env python3
import subprocess
from pathlib import Path

# Phase 3: Unsupervised and Reinforcement Learning + remaining supervised
phase3_content = {
    # Unsupervised Learning
    "modules/module-1.1/2_unsupervised_learning/01-kmeans/README.md": [
        "### K-Means Challenges: Convergence and Initialization Sensitivity\n\nK-means has two critical challenges: convergence guarantees and initialization sensitivity. The algorithm is guaranteed to converge, but only to a local optimum. Different initializations produce different final clusters; some are clearly suboptimal. The k-means++ initialization addresses this probabilistically: instead of random initialization, it selects first centroid randomly, then subsequent centroids with probability proportional to squared distance from nearest existing centroid. This biases toward well-separated starting points, typically producing better solutions. Mathematically, k-means++ gives O(log k) competitive ratio (expected cost ≤ O(log k) × optimal cost), a strong theoretical guarantee. Running k-means++ multiple times with different random seeds and selecting best result is practical. Seeding strategies matter: proper initialization can reduce iterations needed by 50% and dramatically improve final cluster quality. For reproducibility, set random seed explicitly.",
        "### Choosing k: Elbow Method and Silhouette Analysis\n\nSelecting k (number of clusters) is fundamental but challenging; no ground truth exists. The elbow method plots within-cluster sum of squares (WCSS) against k; WCSS decreases monotonically. An elbow (significant slope change) suggests natural k. However, elbows are subjective; many datasets show gradual decreases without clear elbows. Silhouette score measures cluster quality: each sample's silhouette is (b-a)/max(a,b), where a=mean intra-cluster distance, b=mean inter-cluster distance. Silhouette ranges [-1,1]; 1=perfect clustering, 0=overlapping clusters, negative=misclassified. Average silhouette across samples guides k selection: higher average suggests better k. Silhouette is more objective than elbow. Davies-Bouldin index (average similarity between each cluster and most similar cluster) and Calinski-Harabasz index also guide k selection. Cross-validation on downstream tasks (if clustering is preprocessing) might be most principled: select k optimizing final task performance.",
        "### K-Means for Large Datasets: Mini-Batch K-Means\n\nStandard k-means loads all data in memory; for datasets > 1GB, this becomes impractical. Mini-batch k-means processes data in small batches, updating clusters incrementally. Each iteration: (1) Draw random batch; (2) Assign samples to nearest centroids; (3) Update centroid estimates. Memory is O(k*d + batch_size*d), manageable even for huge datasets. Processing is online: data can be streamed. Speed improves significantly: for n samples, k clusters, d dimensions, mini-batch is O(n*k*d*iter) vs standard O(n*k*d*iter) with potentially far fewer iterations. Mini-batch sacrifices some solution quality (slightly suboptimal clusters) for speed and memory efficiency. For billion-sample datasets, mini-batch k-means is necessary. Scikit-learn implements MiniBatchKMeans; batch size is tunable (larger = more accurate but slower).",
        "### Applications: Customer Segmentation and Anomaly Detection\n\nK-means is widely used for customer segmentation: each customer is a point in feature space (purchase history, demographics, behavior); clusters group similar customers. Marketing teams tailor strategies per cluster. Behavioral targeting, personalized recommendations, and pricing strategies differ per cluster. Feature engineering is crucial: raw transaction counts are less informative than derived metrics (average purchase value, purchase frequency, recency). Credit scoring and risk assessment use k-means to segment loan applicants. K-means can detect anomalies: clusters represent normal behavior; points far from all clusters are anomalies. This is simpler than dedicated anomaly detection but less sophisticated. Image compression uses k-means: pixels are points in color space; clustering to k colors and replacing each pixel with cluster center reduces color palette, compressing images. Time series clustering (e.g., stock price patterns) uses k-means with appropriate distance metrics or kernel transformations.",
        "### Limitations and When to Use Alternatives\n\nK-means struggles with non-spherical clusters (elongated, crescent-shaped clusters are poorly handled) and varying cluster sizes. It's also sensitive to outliers: a single outlier can shift centroids significantly. For data with these properties, alternatives are better. DBSCAN handles arbitrary shapes and varying densities. Hierarchical clustering shows structure at multiple scales. Gaussian mixture models provide probabilistic framework with soft assignments. Feature space structure and outlier presence should guide algorithm selection. K-means assumes continuous numerical features; categorical data requires preprocessing (encoding, gower distance). In high dimensions (d > 50), k-means efficiency degrades; dimensionality reduction beforehand helps. K-means is appropriate when: clusters are roughly spherical, sizes similar, no trust in soft assignments, and speed matters. For exploratory analysis, also try hierarchical clustering or DBSCAN to understand structure sensitivity to algorithm choice."
    ],
    "modules/module-1.1/2_unsupervised_learning/02-hierarchical_clustering/README.md": [
        "### Linkage Criteria Comparison and Trade-offs\n\nLinkage criteria define how cluster distances are computed. Single linkage (minimum distance between clusters) emphasizes the role of outliers: a single bridge point connects clusters. This creates long, chain-like clusters. Complete linkage (maximum distance) is conservative: clusters are merged only if all pairs are nearby. It produces compact clusters but may split natural structures. Average linkage computes average distance; it balances single and complete, often producing good results. Ward linkage minimizes within-cluster variance increase; historically popular and often produces well-separated clusters. Centroid linkage uses cluster centroid distances. Empirical comparison shows Ward and average often outperform; try multiple methods via cross-validation. The choice depends on desired cluster shapes: elongated clusters suit single linkage; spherical clusters suit complete/Ward. Domain knowledge and data visualization guide selection. Different linkages on the same data produce different dendrograms; dendrogram shape reveals algorithm preferences.",
        "### Dendrogram Interpretation and Cutting Strategies\n\nDendrograms visualize nested cluster structures; height represents merging distance. Tall vertical lines indicate large jumps in similarity (natural cluster boundaries). The dendrogram visually reveals structure: how clusters subdivide, outliers (long branches from leaves), and meaningful scales. Cutting the dendrogram at different heights produces different numbers of clusters: cutting high (few clusters) produces coarse grouping; cutting low (many clusters) produces fine-grained grouping. The optimal cut height is subjective; visual inspection reveals natural gaps. Automated cutting: choose height maximizing gap between consecutive merges, or fixing number of clusters desired. Dendrograms are invaluable for exploratory analysis: showing which samples cluster together, revealing hierarchical organization, and identifying outliers. Visualization libraries (scipy, seaborn) enable interactive dendrograms: hover to highlight clusters, zoom for details. This interactivity aids exploration and communication with stakeholders unfamiliar with clustering.",
        "### Computational Efficiency and Approximations\n\nHierarchical clustering's O(n² log n) or O(n²) complexity is prohibitive for large datasets. Approximations reduce cost: BIRCH (Balanced Iterative Reducing and Clustering using Hierarchies) builds a hierarchical tree incrementally, achieving O(n) time. CURE (Clustering Using Representatives) selects representative points from each cluster, reducing distance computations. For n = 1M, hierarchical clustering is impractical; alternatives are necessary. Another approach: subsample data (cluster 10% efficiently, then assign remaining points based on subsample clusters). This sacrifices some precision for speed. In practice, hierarchical clustering is used for datasets < 10k samples; larger datasets require alternatives. However, for exploratory analysis, hierarchical clustering on subsampled data often reveals structure.",
        "### Hierarchical Clustering and Other Methods\n\nHierarchical clustering provides rich structural insights unavailable from flat clustering. Combining hierarchical with other methods yields benefits: hierarchical clustering on PCA-reduced data explores non-linear structure; hierarchical clustering followed by k-means on hierarchical clusters (two-step clustering) improves k-means. Consensus clustering applies multiple algorithms (k-means, hierarchical, DBSCAN) and finds stable clusters agreeing across methods. This robustness to algorithm choice is valuable for exploratory analysis. Hierarchical clustering also precedes feature selection: samples in same clusters are similar; features differentiating clusters are likely important. Converting dendrograms to feature importance guides downstream analysis. Overall, hierarchical clustering's richness makes it invaluable for understanding data structure.",
        "### Applications: Taxonomy Construction and Gene Expression\n\nHierarchical clustering is standard in biology for gene expression analysis. Thousands of genes' expression levels (mRNA abundance) are measured across samples. Clustering genes shows co-regulated genes (genes working together); hierarchical structure reveals functional organization. Dendrograms visualize which genes are similar. Mammalian taxonomy is partially constructed via clustering: phylogenetic trees from DNA sequences use hierarchical methods (UPGMA, neighbor-joining), showing evolutionary relationships. Species close in the tree share recent common ancestors. Hierarchical clustering is fundamental in evolutionary biology. In marketing, hierarchical clustering constructs product hierarchies (e.g., clothing categories: apparel → clothing → shirts → t-shirts), useful for e-commerce navigation. Document clustering uses hierarchical methods to organize text corpora into topic hierarchies. A web directory (like older search engines used) is essentially a hierarchy of website categories. These applications showcase hierarchical clustering's power for structured knowledge representation."
    ],
    "modules/module-1.1/2_unsupervised_learning/03-pca/README.md": [
        "### Explained Variance and Choosing Number of Components\n\nThe explained variance ratio for each principal component shows what fraction of total variance it captures. Components are ordered by decreasing variance; the first component is the direction of maximum variance. A scree plot (explained variance for each component) reveals natural cutoffs: choosing components explaining ~90% of variance is standard, though 80% or 95% are common. The cumulative explained variance reaches 90% at component k suggesting k dimensions suffice. However, this assumes linear relationships; nonlinear structure might require more components. In practice, you compute PCA for many components, plot explained variance, choose k manually based on the chart, then recompute PCA with k components. For dimensionality reduction from 100 to 10 dimensions, examining whether 10 components explain 80-95% variance guides whether significant information is retained. The choice balances: reconstruction error (difference between original and reconstructed data) vs computational/interpretability benefits of lower dimensions.",
        "### Centering, Scaling, and Standardization\n\nPCA is sensitive to feature scaling. Features with large variances dominate principal directions. A feature with range [0, 10000] will dominate one with range [0, 1], even if the latter is more informative. StandardScaler (zero mean, unit variance) is essential preprocessing: PCA should be applied to scaled data (via fit-transform on scaled data). Failing to scale is a common mistake producing misleading results. Additionally, PCA centers data (subtracts mean), essential for the covariance matrix computation. Standardization and centering together ensure numerical stability. For features measured in different units (height in cm, weight in kg), scaling is not optional. In scikit-learn, PCA automatically centers data but not scales; always use StandardScaler beforehand.",
        "### Interpretability of Principal Components\n\nPrincipal components are linear combinations of original features; interpreting them reveals feature relationships. For images, PC1 might be 'brightness', PC2 'contrast'. For gene expression, early PCs capture major variation (often broad biological differences); later PCs capture subtle variation (noise or rare biology). Component loadings (coefficients in linear combination) show feature contributions: large positive loading means feature contributes positively; large negative, negatively. Visualizing heatmaps of loadings reveals which features drive each component. This interpretation aids understanding: in healthcare data, if PC1 is heavily loaded on immune markers, PC1 represents immune system state. However, orthogonal constraint (components are perpendicular) sometimes creates components mixing multiple interpretations. A visualization of data projected onto PC1-PC2 plane shows clustering and structure. This two-dimensional representation is invaluable for exploring high-dimensional data.",
        "### PCA for Preprocessing and Denoising\n\nBeyond visualization, PCA removes noise effectively. High-dimensional data's tail (components explaining <1% variance) is mostly noise. Projecting onto leading components, then reconstructing, removes noise without losing structure. This denoising improves downstream algorithms: classification on PCA-reduced features often outperforms original features (noise removed, fewer features reduce overfitting). Sparse PCA selects a subset of original features (rather than all) for components; interpretability improves at slight accuracy cost. Sparse components use fewer features, simpler to explain. Incremental PCA processes data in batches, enabling PCA on datasets too large for memory. This is valuable for streaming data or massive datasets. Mini-batch approach: process chunks, accumulate statistics, finalize PCA. Limited precision (data not seen simultaneously) is acceptable for denoising applications.",
        "### Kernel PCA and Non-linear Structure\n\nStandard PCA finds linear subspaces; if data's structure is non-linear (lie on curves or manifolds), linear subspaces miss structure. Kernel PCA addresses this: implicitly projects data to high-dimensional space via kernels, then applies PCA. RBF kernel enables discovering non-linear structure. A dataset with spiral structure (linear PCA produces tangled projections) is beautifully separated by kernel PCA. However, kernel PCA has computational cost O(n²) (kernel matrix size), and interpreting non-linear components is harder. For non-linear structure, manifold learning (t-SNE, Isomap, UMAP) sometimes outperforms kernel PCA. The tradeoff: kernel PCA provides mathematically principled non-linearity; manifold methods are sometimes more intuitive. When to use: linear structure suggesting standard PCA, non-linear suggesting manifold methods, and when theoretical grounding matters, kernel PCA is appropriate."
    ],
    "modules/module-1.1/2_unsupervised_learning/04-dbscan/README.md": [
        "### Epsilon and Min-Pts Selection: The K-distance Graph\n\nSelecting eps (neighborhood radius) and min_pts (minimum points in neighborhood) is crucial and often requires domain knowledge. The k-distance graph sorts distances to k-th nearest neighbor for each point. For k = min_pts - 1, a scatterplot of sorted distances reveals structure: an elbow suggests eps (threshold separating dense and sparse regions). Points above the elbow are in sparse regions; below are dense. Setting eps at the elbow balances catching all dense points while maintaining cluster distinctions. min_pts is often set to dimensionality + 1 or 2 * dimensionality. In 20-dimensional space with min_pts = 40, neighborhoods require at least 40 samples densely packed; this is stringent, suitable for high-dimensional data. Lower min_pts finds smaller, more numerous clusters; higher min_pts finds larger, fewer clusters. Visualization of eps-neighborhood (all points within distance eps from a point) provides intuition. For well-separated clusters, eps = max distance within cluster. Cross-validation (if density is predictive for the downstream task) can tune eps.",
        "### Handling Varying Density Clusters\n\nA critical DBSCAN limitation: a single eps cannot capture clusters of varying densities. Dense clusters require small eps; sparse clusters require large eps. With moderate eps, dense clusters are divided; with large eps, sparse clusters merge. HDBSCAN (Hierarchical DBSCAN) extends DBSCAN by building a hierarchy of clustering solutions for different eps values, then extracting stable clusters. The hierarchy reveals structure at multiple density levels. OPTICS (Ordering Points to Identify Clustering Structure) computes a density-based ordering without fixing eps. The OPTICS plot (distance values for each point) reveals density changes; natural cutoffs show cluster boundaries. Both HDBSCAN and OPTICS handle varying densities better than DBSCAN. For applications with known multi-density structure, these variants are preferable.",
        "### Computational Complexity and Spatial Indexing\n\nDBSCAN has O(n²) complexity without spatial indexing; with KD-trees or ball-trees, it's O(n log n) on average. For very large datasets, spatial indexing is essential else DBSCAN is slow. Scikit-learn's DBSCAN automatically uses ball-trees if datasets are large; for custom applications, implementing indexing improves performance significantly. Memory is O(n) for storing the index plus O(n) for distance computations; manageable for most datasets. The advantage over k-means: DBSCAN identifies noise without forcing all points into clusters. For anomaly detection, noise points are the anomalies, making DBSCAN appropriate. For k-means-like clustering without specifying k, DBSCAN is convenient; no need to search multiple k values.",
        "### Real-world Applications: Spatial Clustering\n\nDBSCAN is foundational in spatial data mining: geographic information, GPS trajectories, and sensor networks. Grouping GPS points into locations (home, work, favorite restaurants) is a classic application. DBSCAN identifies meaningful places (dense regions of visits) and filters noise (transient locations). In traffic analysis, clustering congested regions reveals critical roads. In astronomy, clustering stars reveals galaxy structures. Text clustering with appropriate similarity metrics (e.g., cosine similarity on TF-IDF): documents cluster by topic; noise documents are outliers. DBSCAN's noise handling is valuable: identified outliers warrant investigation (spam documents, fraudulent transactions). The algorithm's simplicity, lack of requiring cluster number specification, and natural noise detection make it practical.",
        "### Quality Metrics and Validation\n\nEvaluating DBSCAN clustering is non-trivial; traditional metrics assume well-separated clusters. Silhouette score can be used but may be misleading with noise. Davies-Bouldin index focuses on clusters (ignoring noise). Noise-aware metrics: fraction of points identified as noise (compared to domain expectation), cluster stability (similar clusters across parameter variations). Cross-validation: if clustering enables downstream tasks (classification on cluster features), validation on task performance is most useful. For exploratory analysis without ground truth, visual inspection of clustering results guides parameter selection. Plotting data (2D projection via PCA or t-SNE) shows whether clusters are meaningful and separated. Comparing DBSCAN to k-means and hierarchical clustering via multiple metrics provides robustness: consensus across methods suggests meaningful structure."
    ],
    "modules/module-1.1/2_unsupervised_learning/05-gaussian_mixture_models/README.md": [
        "### EM Algorithm Convergence and Local Maxima\n\nThe Expectation-Maximization algorithm monotonically increases likelihood but converges to local maxima (not guaranteed global). Starting from poor initializations, EM can converge to poor solutions. Multiple random restarts are necessary: run EM from 10 different initializations, select maximum likelihood result. Poor solutions are identified by low likelihood compared to restarts or fit quality. Tuning number of iterations: EM usually converges quickly (10-50 iterations). Monitoring log-likelihood reveals convergence: stable log-likelihood over iterations indicates convergence. Early stopping criteria (tolerance on likelihood change) prevent unnecessary iterations. Scaled versions of data improve numerical stability; features with different scales cause numerical issues. Responsibility values (soft assignments) should be checked: if a component has near-zero assigned samples, that component isn't learning (degenerate). Careful initialization via k-means preprocessing helps avoid degeneracy.",
        "### Determining Optimal Number of Components\n\nSelecting k (number of Gaussian components) uses information criteria. Bayesian Information Criterion (BIC) balances likelihood (fit) and complexity (parameter count): BIC = -2 * log(L) + p * log(n). Lower BIC indicates better fit relative to complexity. Akaike Information Criterion (AIC) uses: AIC = -2 * log(L) + 2 * p. AIC penalizes complexity less than BIC; for large n, BIC is preferred. Cross-validation: split data, train on k-1 folds, evaluate on k-th fold via likelihood. Averaging across folds provides robust estimate; choose k minimizing cross-validation error. Unlike k-means (no natural likelihood), GMM's probabilistic framework enables principled model selection. Plotting BIC/AIC/cross-validation error vs k reveals elbow; this elbow suggests optimal k. Running grid search over k values (e.g., k in 1:20) with cross-validation is standard practice.",
        "### Covariance Matrix Constraints and Regularization\n\nGMM with full covariance matrices (unconstrained) has O(k * d²) parameters; for d = 100 and k = 10, this is thousands of parameters. With limited data, this overfits. Constraints reduce parameters: spherical covariance (σ² * I, same variance all directions) has k parameters. Diagonal covariance (σ²_d per dimension) has k * d parameters. Full covariance (most flexible) has k * d * (d+1) / 2 parameters. Constraints are selected based on data and computational resources. For d > 100 (high-dimensional), diagonal or spherical is necessary. Regularization: adding small constant to diagonal prevents singular covariance matrices (numerical issues). In scikit-learn, covariance_type parameter selects constraint. Empirically trying multiple types via cross-validation finds best fit.",
        "### Probabilistic Interpretation and Soft Clustering\n\nUnlike k-means (hard assignments), GMM provides soft assignments: each sample has probability vector over components. This probability represents uncertainty: probability [0.9, 0.05, 0.05] means sample is likely component 1 but somewhat uncertain. Soft assignments are valuable for uncertainty quantification, probabilistic inference, and downstream applications requiring confidence. Samples on cluster boundaries get intermediate probabilities. This inherent uncertainty is useful: critical decisions (medical diagnosis) use high-confidence predictions, uncertain cases warrant manual review. Soft assignments enable smooth boundaries: moving a sample gradually through space results in gradual probability changes (unlike k-means discontinuity). For generative modeling: GMM defines a distribution; sampling from GMM creates synthetic data. Component selection (sample from component probability) followed by Gaussian sampling generates realistic data.",
        "### Applications: Density Estimation and Anomaly Detection\n\nGMM's probabilistic framework enables density estimation: P(x) = Σ π_k * N(x | μ_k, Σ_k), fully specifying data distribution. This enables likelihood computation for any sample; likelihood quantifies how typical the sample is. Anomalies have low likelihood. This is a principled approach to anomaly detection versus k-means clustering. In quality control, product features follow a distribution (normal operation); products with low likelihood under learned GMM are defective. In cybersecurity, network traffic patterns are learned via GMM; attacks have low likelihood. This probabilistic approach is more theoretically grounded than distance-based methods. GMM also enables missing data imputation: conditional expectations given partial observations impute missing values. For example, imputing missing gene expression values from partially observed samples. Overall, GMM's probabilistic nature enables sophisticated downstream tasks beyond clustering."
    ],
    "modules/module-1.1/2_unsupervised_learning/06-manifold_learning/README.md": [
        "### t-SNE Perplexity and Convergence Tuning\n\nt-SNE has two key hyperparameters: perplexity (effective neighborhood size, typically 5-50) and learning rate. Perplexity roughly equals: effective neighborhood size for distance computations. Small perplexity (5-10) focuses on local structure; large perplexity (50+) emphasizes global structure. The trade-off is non-trivial: small perplexity often produces fragmented clusters; large perplexity can blur cluster boundaries. Typical choice is perplexity = 30, though tuning by visualization is common. t-SNE is sensitive to hyperparameters; slightly different settings produce noticeably different visualizations. Early exaggeration (multiplying attractive forces initially) helps separate clusters. Multiple runs with different random seeds produce different layouts; variations are expected. t-SNE usually requires hundreds of iterations to converge; monitoring loss (KL-divergence) reveals convergence. Computation is O(n²), making t-SNE slow for n > 10k (approximate versions like Barnes-Hut speed it up to O(n log n)).",
        "### Isomap and Geodesic Distances\n\nIsomap addresses PCA's limitation when data lies on non-linear manifolds. Computing geodesic distances (along the manifold) rather than Euclidean distances (through space) better captures intrinsic dimensionality. Procedure: (1) Build k-NN graph (connect each point to k nearest neighbors); (2) Compute shortest paths using Dijkstra's algorithm; (3) Apply classical scaling to geodesic distance matrix. Geodesic distances approximate true manifold distances; the k-NN graph reconstruction quality depends on k. Small k (too local) fragments graph; large k (too global) ignores manifold curvature. The number of components k is chosen via explained variance similar to PCA. Isomap provides stable dimension estimates (how many dimensions the manifold truly has) via spectral analysis. The algorithm scales as O(n³) (all-pairs shortest paths), limiting n to ~10k. For very large datasets, approximate Isomap or other methods are necessary.",
        "### Locally Linear Embedding and Local Structure Preservation\n\nLLE (Locally Linear Embedding) assumes each neighborhood lies near a linear patch of the manifold. Algorithm: (1) For each point, minimize reconstruction error (distance from point to linear combination of neighbors); (2) Weights capture local linear structure; (3) Apply these weights to low-dimensional embeddings, preserving local relationships. High-dimensional local linearity implies low-dimensional local linearity; this principle underlies LLE. Unlike Isomap (which requires computing all-pairs distances), LLE only requires k-NN neighbors, scaling better. Parameter k (neighborhood size) is crucial: too small (noisy), too large (destroys local structure). Number of components is chosen similarly to PCA. LLE often produces interpretable embeddings; nearby samples in input space remain nearby in embedding. However, unlike t-SNE, LLE doesn't emphasize cluster separation; it focuses on preserving local geometry.",
        "### UMAP: Improved Manifold Learning\n\nUniform Manifold Approximation and Projection (UMAP) is a modern alternative to t-SNE addressing limitations. UMAP uses spectral methods to preserve both local and global structure better than t-SNE. It's faster (O(n) approximately) via graph-based approximations. UMAP has fewer hyperparameters than t-SNE (n_neighbors, min_dist). n_neighbors controls neighborhood size (similar to perplexity); min_dist controls minimum separation between points. UMAP produces stable visualizations: different runs produce similar layouts. This stability is advantageous for reproducibility and deployment. UMAP preserves global structure better than t-SNE: distant clusters remain distant. This makes UMAP more suitable than t-SNE for exploratory analysis where global understanding matters. Visualizations are often more interpretable. UMAP also provides an inverse transform: new points can be projected; t-SNE cannot. These advantages make UMAP increasingly preferred over t-SNE.",
        "### Manifold Learning for Feature Discovery and Visualization\n\nManifold learning is invaluable for exploratory analysis: visualizing high-dimensional data in 2D/3D reveals structure. Clusters, outliers, continuous gradients become apparent. For datasets with known classes (e.g., images), visualizations show if classes cluster (good separability) or mix (challenging classification). Manifold learning also discovers meaningful features: low-dimensional embeddings can train downstream models efficiently. Using t-SNE-reduced features for classification sometimes outperforms original features (noise removed, lower-dimensional structure emphasized). However, fine-tuning manifold parameters is non-trivial; visualizations depend heavily on hyperparameters. Always try multiple hyperparameters to ensure robustness: if structure disappears with slightly different parameters, it might be artificial. Combining manifold methods (t-SNE and UMAP together) provides confidence in structure genuineness. Overall, manifold learning is essential for understanding complex data structure."
    ],
    # Reinforcement Learning
    "modules/module-1.1/3_reinforcement_learning/01-qlearning/README.md": [
        "### The Bellman Equation and Dynamic Programming\n\nThe Bellman equation V(s) = E[R(s) + γV(s')] expresses the value of a state as immediate reward plus discounted future value. This recursive relationship is the foundation of dynamic programming in RL. If transition probabilities and rewards are known (model-based), iterative application of Bellman updates computes optimal values. Value iteration: V_{t+1}(s) = E[R(s) + γ max_a V_t(s')] computes values by repeatedly updating. Policy iteration alternates between evaluating policy (computing values for current policy) and improving policy (greedily selecting best actions). Both converge to optimal values. However, both require knowing model (transition probabilities); Q-learning doesn't, learning from experience. Q-learning directly estimates Q-values satisfying Bellman optimality: Q*(s,a) = E[R + γ max_a' Q*(s',a')]. The connection is deep: Q-learning in tabular form is model-free dynamic programming.",
        "### ε-Greedy, Softmax, and Exploration Strategies\n\nε-Greedy exploration: take greedy action (highest estimated Q) with probability 1-ε, random action with probability ε. Simple and effective; ε-decay (decreasing ε over time) starts exploratory, becomes exploitative. Decaying ε from 1 to 0 over thousands of episodes balances exploration and exploitation. Softmax exploration: select actions probabilistically proportional to exp(Q(s,a)/τ). Temperature τ controls randomness; τ → 0 approaches greedy, τ → ∞ approaches uniform random. Softmax is smooth unlike ε-greedy's discontinuity. Upper Confidence Bound (UCB) balances exploration and exploitation through uncertainty: prioritize actions with high uncertainty (not yet explored) and high estimated value. UCB: a = arg max [Q(a) + c * √(ln(t) / N(a))], where N(a) is times action a taken, t is total timesteps. This naturally decays exploration as actions are well-understood. Optimistic initialization: initialize Q-values optimistically (high values); incentivizes exploring to confirm or revise. Each strategy has trade-offs: ε-greedy is simple, softmax is smooth, UCB is principled, optimistic initialization is elegant.",
        "### Experience Replay and Target Networks in Deep RL\n\nApplying neural networks directly to Q-learning's temporal difference learning is unstable: targets constantly change as network updates. Experience replay addresses this: store (s, a, r, s') in memory buffer, sample random minibatches for training. Random sampling breaks temporal correlations; IID samples satisfy gradient descent assumptions. Minibatch updates (averaging over multiple samples) reduce variance. Target networks: maintain a separate network for computing targets, updated infrequently (every C steps or slowly with weight decay). During training, main network updates to match targets from fixed target network, providing stable targets. Combining experience replay and target networks stabilizes training substantially; DQN (Deep Q-Network) applies these techniques to Atari games, achieving superhuman performance. Memory requirements are non-trivial: storing millions of transitions requires gigabytes. Prioritized experience replay samples high temporal-difference error transitions more frequently, improving sample efficiency.",
        "### Double Q-Learning and Overestimation\n\nQ-learning tends to overestimate action values: selecting max_{a'} Q(s', a') uses same network for both action selection and evaluation. Double Q-learning decouples selection and evaluation: select action via a* = argmax_a Q(s', a'; θ), evaluate via Q(s', a*; θ_target). This reduces overestimation by ~50% empirically. The improvement is subtle but consistent: overestimation causes agents to prefer actually-bad actions incorrectly. Double Q-learning is simple (one line code change) and significantly improves performance and stability. Dueling Q-networks decompose Q-values into state value V(s) and advantage A(s,a): Q(s,a) = V(s) + A(s,a) - mean_a A(s,a). Advantages (action advantages) are centered; this representation is more stable. Dueling architecture enables networks to focus on value estimates and advantage estimates separately, improving learning. Combining double and dueling Q-learning with prioritized experience replay creates Rainbow DQN achieving near-superhuman Atari performance.",
        "### From Tabular to Function Approximation\n\nTabular Q-learning (separate Q value for each state-action pair) is practical only for discrete, small state spaces. For continuous states or large discrete spaces (chess: 10⁴³ states), tabular is infeasible. Function approximation: represent Q(s,a) ≈ f(s,a; θ) with neural network parameters θ. Q-values for unseen states are generalized from nearby states. This enables learning in complex environments (images as input, continuous states). Function approximation introduces new challenges: (1) non-stationary targets (network changes, targets change); (2) function approximation errors compound (errors in one state affect nearby states); (3) convergence proofs don't apply (non-convex optimization, feature interactions). Modern deep RL addresses these via experience replay, target networks, and careful architecture design. Function approximation's generalization benefit (learning structure from limited data) outweighs challenges, enabling learning in complex environments."
    ],
    "modules/module-1.1/3_reinforcement_learning/02-policy_gradient/README.md": [
        "### Policy Gradient Theorem and Gradient Computation\n\nThe policy gradient theorem states: ∇_θ J(θ) = E[∇_θ log π(a|s; θ) Q(s,a)]. This elegant result connects policy gradients to value functions. The key insight: ∇_θ log π(a|s; θ) points in direction increasing action probability. Multiplying by Q(s,a) (advantage of action) weights this by actual goodness. For high Q (good action), prob increases; for low Q, prob decreases. The gradient is easy to compute for any differentiable policy. For neural network policies, log probability is typically cross-entropy loss (categorical for discrete actions, Gaussian log-density for continuous). The beauty: no need to estimate true Q function; approximation Q̂ is sufficient (introduces bias but reduces variance). The trade-off: better Q approximations reduce bias; worse approximations reduce variance. Average between two extremes is optimal.",
        "### Advantage Estimation and GAE\n\nPolicy gradients use advantage A(s,a) = Q(s,a) - V(s), representing action preference relative to baseline. Baseline V(s) reduces variance without adding bias; policies better than baseline get positive advantages, worse get negative. This significantly improves sample efficiency. Computing advantages: one-step temporal difference A(s,a) = r + γV(s') - V(s) is low-variance but biased. n-step returns A = Σ γ^k r_{t+k} + γ^n V(s_{t+n}) - V(s_t) are higher-variance, lower-bias. Generalized Advantage Estimation (GAE) interpolates: A_t = Σ_{l=0}^∞ (γλ)^l δ_{t+l}, where δ = r + γV(s') - V(s). Parameter λ ∈ [0,1] controls: λ=0 is one-step (high bias, low variance), λ=1 is full return (low bias, high variance). Empirically λ=0.95 often works well, balancing bias and variance. GAE provides principled advantage estimation crucial for stable training.",
        "### Trust Region Policy Optimization and PPO\n\nUnconstrained policy gradient updates can cause large parameter changes, degrading performance. Trust region methods constrain updates: TRPO (Trust Region Policy Optimization) restricts KL divergence between old and new policies: constrain KL(π_old || π_new) ≤ δ. Solving this constrained optimization exactly is complex; conjugate gradient methods approximately solve. PPO (Proximal Policy Optimization) simplifies via clipping: instead of enforcing constraint, clip probability ratios to [1-ε, 1+ε]. The clipped objective is min[r_t * A_t, clip(r_t, 1-ε, 1+ε) * A_t], where r_t = π(a|s; θ) / π(a|s; θ_old). Clipping prevents destructively large updates while enabling beneficial updates. PPO is simpler than TRPO (no second-order derivatives), faster, and empirically outperforms. PPO has dominated recent deep RL; nearly all modern results use PPO or variants. The simplicity and effectiveness make PPO the default policy gradient algorithm.",
        "### Actor-Critic Architecture Integration\n\nCombining policy gradients with value estimation: actor (policy) selects actions, critic (value network) estimates values. The critic provides advantage estimates for policy gradient updates, significantly reducing variance. During training: (1) Actor generates trajectories; (2) Critic estimates values; (3) Compute advantages (critic outputs); (4) Update actor using policy gradients with advantages; (5) Update critic to better estimate values. This two-network architecture is powerful: each network focuses on its task (action selection vs value estimation), improving learning. A3C (Asynchronous Advantage Actor-Critic) parallelizes by running multiple agents in parallel environments, accumulating gradients, then applying to global actor-critic. Parallelization accelerates learning substantially without synchronized sampling. A3C and variants (A2C, PPO) are fundamental in modern deep RL.",
        "### Entropy Regularization and Exploration\n\nPolicy gradient methods risk converging to deterministic policies (low entropy): without exploration incentive, the agent exploits known good actions. Entropy bonus: add -β * H(π) to objective, where H = -Σ π(a|s) log π(a|s). This encourages maintaining randomness; high entropy means close to uniform (maximum randomness), low entropy means concentrated. β (entropy coefficient) controls randomness strength; typical values 0.001-0.1. Higher β = more randomness, lower = more exploitation. As learning progresses, gradually decreasing β enables initial exploration followed by exploitation. Entropy regularization naturally balances exploration-exploitation without explicit ε-greedy. It's more principled than ε-greedy: the agent learns exploration amount. In games (Atari, Go), entropy regularization is essential: purely greedy learns narrow strategies; entropy-regularized explores diverse strategies, often discovering better solutions. The interplay between value optimization and entropy regularization is delicate; careful tuning is necessary."
    ],
    "modules/module-1.1/3_reinforcement_learning/03-actor_critic/README.md": [
        "### GAE Implementation and Advantage Normalization\n\nImplementing Generalized Advantage Estimation requires accumulating rewards and values along trajectories. For each timestep t: δ_t = r_t + γV(s_{t+1}) - V(s_t). GAE advantages: A_t = Σ_{l=0}^∞ (γλ)^l δ_{t+l}. Computationally: A_t = δ_t + γλ * A_{t+1}, computed backward from episode end. This recursion is efficient. Advantage normalization (subtracting mean, dividing by std) standardizes advantages across episodes, stabilizing learning. Without normalization, advantage magnitudes vary widely (different episode lengths, reward scales); normalization ensures consistent gradient magnitudes. In practice: compute all advantages for batch, normalize, then update networks. This preprocessing step significantly improves convergence.",
        "### A2C vs A3C: Synchronous vs Asynchronous Learning\n\nA2C (Advantage Actor-Critic) is synchronous: collect experiences from n parallel environments, compute gradients from all n, then apply updates. This is efficient with distributed computing. A3C (Asynchronous Advantage Actor-Critic) is truly asynchronous: each worker independently runs environment, computes gradients, applies to global network. No synchronization needed; agents start updating at different times. A3C's asynchrony enables parallelization without specialized distributed infrastructure; each worker is independent. Both achieve similar final performance; A2C is more efficient with proper distributed setup, A3C is simpler to implement. In modern frameworks (PyTorch with distributed data parallel), A2C-style architecture is easier. The asynchronous nature of A3C doesn't matter if underlying compute is synchronized anyway.",
        "### Continuous Action Spaces: Gaussian Policies\n\nFor continuous action spaces (robot control, autonomous vehicles), policies output continuous actions. Gaussian policies are standard: the network outputs mean μ(s) and std σ(s) for action distribution. Actions are sampled: a ~ N(μ(s), σ²(s)). Log-probability: log π(a|s) = -0.5 * log(2π) - log(σ) - 0.5 * ((a-μ)/σ)². Policy gradient updates are straightforward; the network learns to output appropriate means and stds. σ can be state-dependent or globally learned.  State-dependent stds enable adaptive exploration; exploratory actions where uncertain, deterministic where confident. For stability, σ is often represented as log σ (unconstrained) or bounded via softplus. Another approach: squashing network output via tanh to [-1,1], appropriate for bounded actions (e.g., robot joint limits). Transformed policy gradients account for Jacobian of squashing transformation.",
        "### Distributional Perspectives and Value Range\n\nTradition actor-critic estimates scalar values V(s). Distributional RL estimates full return distributions, not just expectations. This richer representation improves learning: agents understand return variance (uncertainty about future rewards). Categorical distributional RL represents returns as discrete probability distributions over value bins. QR-DQN uses quantile regression, learning quantiles of return distributions. These approaches show empirical improvements and theoretical benefits: better exploration (high-uncertainty actions), more robust to outliers, improved credit assignment. However, implementation is more complex; most practitioners use simplified scalar value functions. State-of-the-art methods (Rainbow DQN) combine distributional approaches with other improvements; the synergy contributes to strong performance.",
        "### Actor-Critic Applications and Benchmarks\n\nModern benchmarks (OpenAI Gym, DeepMind Control Suite, Atari, robotics simulators) evaluate RL algorithms. Actor-critic methods consistently rank among top performers. PPO (a policy gradient variant with trust regions) is dominant due to simplicity and reliability. SAC (Soft Actor-Critic) uses entropy regularization and distributional perspectives, achieving impressive continuous control results. Robotics simulators (MuJoCo, Bullet) test continuous control; actor-critic methods excel. In game-playing, policy gradients (with distributed training) match or exceed value-based methods (DQN). The practical dominance of actor-critic reflects its balance of simplicity, stability, and sample efficiency. For practitioners starting RL, implementing and tuning PPO or A2C is recommended."
    ],
    "modules/module-1.1/3_reinforcement_learning/04-deep_q_networks/README.md": [
        "### DQN Variants: Dueling, Double, and Noisy Networks\n\nDueling DQN decomposes Q = V + (A - mean{A}), separating state value and advantage. This architectural change improves learning: the network learns value and advantages separately, focusing learning signals on relevant parts. Empirically, dueling improves performance, particularly when advantages are similar (many actions give similar rewards). Double DQN addresses overestimation via decoupled action selection and evaluation. Noisy networks add learnable noise to weights rather than ε-greedy exploration. The noise is sample-specific (different noise per forward pass), enabling exploration. Unlike ε-greedy (sudden randomness), noisy networks provide continuous exploration. These variants can be combined (dueling + double + noisy = strong ensemble). Empirically, all three improve DQN. Rainbow DQN combines these plus prioritized replay and distributional RL, achieving near-superhuman Atari performance.",
        "### Atari 2600 Benchmark and Model Capacity\n\nAtari games (57 games) form a standard benchmark for deep RL. DQN's breakthrough was achieving superhuman performance on multiple games without game-specific engineering. Raw pixels (84x84 grayscale images) are inputs; game scores are rewards. The challenge: learning from high-dimensional perceptual input and delayed rewards. DQN's success inspired massive follow-up research. Modern methods (Rainbow DQN, MuZero) achieve far higher scores. The benchmark's difficulty lies in: (1) Long credit assignment (rewards come many steps after actions); (2) Sparse rewards (long stretches without reward); (3) Complex state spaces (many possible situations). Analyzing which games are hard: sparse-reward games (Montezuma's Revenge) remain challenging; reward-rich games are solved. This drives algorithm development toward better credit assignment and exploration.",
        "### Continuous Control and DQN Limitations\n\nDQN is designed for discrete action spaces; extending to continuous is non-trivial. Naive approach: discretize continuous actions (e.g., joint angles into 10 bins), apply DQN. This wastes action space resolution and doesn't scale (3 joints × 10 bins = 1000 actions; 5 joints with 10 bins = 100k actions; curse of dimensionality). SVG (Stochastic Value Gradient) extends DQN to continuous actions via differentiable action selection; policy gradient on Q-values. DDPG (Deep Deterministic Policy Gradient) combines ideas: networks output deterministic actions, advantage is q gradient. A3C/PPO (policy gradient methods) naturally handle continuous actions via Gaussian policy outputs. For continuous control, policy gradients are more appropriate than value-based methods; this is why continuous benchmarks (MuJoCo, robotics simulators) use A3C, PPO, SAC rather than DQN variants.",
        "### Model-Based RL and DQN Comparison\n\nDQN is model-free: it learns value functions from experience without learning environment model (dynamics). Model-based RL learns transition model p(s'|s,a), enabling planning: imagine action sequences, predict outcomes, select sequences with best predicted returns. Model-based advantages: sample efficiency (learning dynamics from fewer samples enables many planning simulations). Model-based disadvantages: model errors compound (wrong predictions after 100 steps are unreliable); learning environment models is hard (unpredictable stochasticity). Recent work (AlphaZero, MuZero) combines both: learning implicit value functions via dynamics prediction without explicit model. Practical applications favor model-free in high-stochasticity environments (games, robotics); model-based in low-stochasticity environments (planning, control with known physics).",
        "### Deployment and Real-time Constraints\n\nDeploying DQN in production (robotics, autonomous systems) involves challenges: inference speed (real-time constraints), model size (embedded devices), robustness (adversarial perturbations). Standard DQN networks (convolutional + fully-connected) are moderately sized; inference is typically milliseconds on GPUs. For real-time systems (robot control at 50Hz = 20ms per decision), inference must be fast. Model compression (quantization, pruning, distillation) reduces size and speeds inference. Robustness to adversarial perturbations (small input changes causing large output changes) is a concern: adversarial examples cause misclassification. Certified defenses ensure robustness but reduce performance. In practice, deploying learned agents in uncontrolled environments risks surprising failures. Hybrid approaches (learning + planning, learning + rule-based fallbacks) increase reliability. The gap between powerful learning algorithms and robust deployed systems remains significant."
    ]
}

def add_phase3_content():
    """Add Phase 3 content (remaining algorithms)."""
    total = 0
    
    for filepath, content_list in phase3_content.items():
        try:
            path = Path(filepath)
            if not path.exists():
                print(f"[!] {filepath} not found")
                continue
            
            for i, paragraph in enumerate(content_list, 1):
                with open(path, 'a', encoding='utf-8') as f:
                    f.write("\n\n" + paragraph)
                
                subprocess.run(['git', 'add', str(path)], capture_output=True)
                alg_name = path.parent.name.replace('-', ' ').title()
                commit_msg = f"Expand {alg_name} lessons - Advanced content paragraph {i}/5"
                subprocess.run(['git', 'commit', '-m', commit_msg], capture_output=True)
                print(f"[+] {alg_name} paragraph {i}/5")
                total += 1
        except Exception as e:
            print(f"Error with {filepath}: {e}")
    
    return total

print("Phase 3: Expanding unsupervised and RL lessons...\n")
commits = add_phase3_content()
print(f"\n[OK] Added {commits} commits in Phase 3")
