import gradio as gr
import numpy as np
import pandas as pd

import joblib

model = joblib.load("rf_model.joblib")

# --- Prediction & Advice Logic ---
def predict_and_advise(age, systolic_bp, diastolic_bp, blood_sugar, body_temp, heart_rate):
    # 1. Create DataFrame matching training format
    input_data = pd.DataFrame([{
        'Age': age,
        'SystolicBP': systolic_bp,
        'DiastolicBP': diastolic_bp,
        'BS': blood_sugar,
        'BodyTemp': body_temp,
        'HeartRate': heart_rate
    }])
    
    # 2. Replicate your exact Feature Engineering
    input_data['PulsePressure'] = input_data['SystolicBP'] - input_data['DiastolicBP']
    input_data['MAP'] = input_data['DiastolicBP'] + ((input_data['SystolicBP'] - input_data['DiastolicBP']) / 3)
    input_data['HighBS'] = (input_data['BS'] >= 8.0).astype(int)
    
    # 3. Generate Prediction using your trained model variable ('model')
    pred_numeric = model.predict(input_data)[0]
    
    # 4. Define Clinical Context based on the predicted risk tier
    if pred_numeric == 0:
        status_tier = "🟢 LOW RISK"
        summary = f"Vitals present within stable, acceptable boundaries for a {age}-year-old patient."
        suggestions = (
            "* **Routine Monitoring:** Continue regular prenatal check-ups as scheduled by your doctor.\n"
            "* **Lifestyle:** Maintain a balanced diet, stay well-hydrated, and engage in safe, low-impact prenatal exercises.\n"
            "* **Log Vitals:** Keep tracking blood pressure and sugar weekly to establish a healthy baseline."
        )
    elif pred_numeric == 1:
        status_tier = "🟡 MID RISK"
        summary = f"Some vital signs (e.g., Blood Pressure: {systolic_bp}/{diastolic_bp} or Blood Sugar: {blood_sugar} mmol/L) are borderline or fluctuating outside ideal windows."
        suggestions = (
            "* **Alert Care Provider:** Share these exact readings with your OB-GYN or primary midwife at your earliest convenience.\n"
            "* **Dietary Adjustments:** Consider monitoring carbohydrate and sodium intake closely.\n"
            "* **Frequent Screening:** Increase vitals tracking to daily (morning and evening) to detect patterns."
        )
    else:
        status_tier = "🔴 HIGH RISK"
        summary = f"Critical thresholds detected! Vitals signify a highly elevated risk profile requiring urgent clinical review."
        suggestions = (
            "* **Immediate Medical Attention:** Contact your maternal care unit, OB-GYN, or visit an urgent care clinic immediately.\n"
            "* **Rest & Limit Stress:** Sit or lie down on your left side, remain calm, and avoid physical exertion.\n"
            "* **Prepare Records:** Keep a written or digital log of your recent symptoms and these numbers ready for the medical team."
        )
        
    disclaimer_text = (
        "⚠️ **CRITICAL MEDICAL DISCLAIMER:** This software is an automated AI classification system "
        "built for analytical and educational screening purposes. It is **NOT** a substitute for professional "
        "medical advice, diagnosis, or treatment. Never disregard, delay, or ignore professional medical advice "
        "from your doctor or healthcare provider because of something generated by this application."
    )
    
    # Return the data and change the box container visibility to True
    return status_tier, summary, suggestions, disclaimer_text, gr.update(visible=True)


# --- Build Gradio UI Interface ---
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🤰 Maternal Health Risk Assessment (Random Forest Optimized)")
    gr.Markdown("Input patient vital signs below to run an instant diagnostic screening via the optimized Random Forest framework.")
    
    with gr.Row():
        # Left Side: Input Panel
        with gr.Column(scale=1):
            gr.Markdown("### 🩺 Vital Signs Input Form")
            age = gr.Slider(minimum=10, maximum=70, value=25, step=1, label="Age (years)")
            systolic_bp = gr.Number(value=120, label="Systolic Blood Pressure (mmHg)")
            diastolic_bp = gr.Number(value=80, label="Diastolic Blood Pressure (mmHg)")
            blood_sugar = gr.Number(value=7.5, label="Blood Sugar / Glucose (mmol/L)")
            body_temp = gr.Number(value=98.0, label="Body Temperature (°F)")
            heart_rate = gr.Number(value=75, label="Heart Rate (bpm)")
            
            submit_btn = gr.Button("Analyze Patient Risk Profile", variant="primary")
            
        # Right Side: Hidden Output Panel (Becomes visible only after execution)
        with gr.Column(scale=1):
            with gr.Column(visible=False) as results_container:
                gr.Markdown("### 📊 Assessment Output")
                output_tier = gr.Textbox(label="Predicted Risk Category", interactive=False)
                
                gr.Markdown("---")
                gr.Markdown("### 📋 General Case Information")
                output_summary = gr.Markdown()
                
                gr.Markdown("### 💡 Recommended Next Steps & Suggestions")
                output_suggestions = gr.Markdown()
                
                gr.Markdown("---")
                output_disclaimer = gr.Markdown()

    # Link button click to the layout
    submit_btn.click(
        fn=predict_and_advise,
        inputs=[age, systolic_bp, diastolic_bp, blood_sugar, body_temp, heart_rate],
        outputs=[output_tier, output_summary, output_suggestions, output_disclaimer, results_container]
    )

# Launch the interactive web app
demo.launch()